#!/bin/sh

set -e

case "$1" in
    purge|remove)
    su -c 'dbus-send --type=method_call --dest=org.hildon.eventfeed /org/hildon/eventfeed org.hildon.eventfeed.removeRefreshAction string:/opt/rssevents/bin/rssevents' - user
    ;;
    
    *)
    
    ;;
esac

exit 0
